server {
    listen 443 ssl;
    server_name app.devho.st;
    
    ssl_certificate     /etc/nginx/certs/app.devho.st.crt;
    ssl_certificate_key /etc/nginx/certs/app.devho.st.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
}